# Generated by Django 5.0 on 2024-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_alter_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
